use anyhow::{Context as _, Result};
use gpt_oss_tokenizer::render_then_encode;
use openai_harmony::chat::{Message, Role};
use std::path::PathBuf;
use std::process::Command;

fn expand_tilde(p: &str) -> PathBuf {
    use std::path::{Path, PathBuf};
    if let Some(rest) = p.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return Path::new(&home).join(rest);
        }
    }
    PathBuf::from(p)
}

const SNAPSHOT: &str = "~/.cache/huggingface/hub/models--openai--gpt-oss-20b/snapshots/6cee5e81ee83917806bbde320786a8fb61efebee";

#[test]
fn t04_tokenizer_parity_with_python() -> Result<()> {
    // Build the rendered prompt via Harmony + Jinja + tokenizer.json (Rust path)
    let snapshot = expand_tilde(SNAPSHOT);
    let msg = Message::from_role_and_content(
        Role::User,
        "Explain what MXFP4 quantization is".to_string(),
    );
    let ids_rust = render_then_encode(&snapshot, &[msg], true /* add_generation_prompt */)
        .context("render_then_encode failed")?;
    assert!(!ids_rust.is_empty(), "prompt tokens should not be empty");

    // Ask Python HF tokenizer to render and encode the same prompt, using the snapshot.
    // Keep it local/offline and cheap (no model load).
    let script = {
        format!(
            r#"import json, sys
from transformers import AutoTokenizer
snap = {snap}
tok = AutoTokenizer.from_pretrained(snap, trust_remote_code=True, local_files_only=True)
messages = [{{"role": "user", "content": "Explain what MXFP4 quantization is"}}]
rendered = tok.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)
ids = tok.encode(rendered, add_special_tokens=False)
print(json.dumps(ids))
"#,
            snap = format!("{:?}", snapshot.display()),
        )
    };
    let output = Command::new("uv")
        .args(["run", "python", "-c", &script])
        .env("PYTHONUNBUFFERED", "1")
        .env("TRANSFORMERS_OFFLINE", "1")
        .env("HF_HUB_OFFLINE", "1")
        .output()
        .context("failed to run uv python for HF tokenizer parity")?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("python failed: {}", stderr);
    }
    let py_ids: Vec<u32> =
        serde_json::from_slice(&output.stdout).context("invalid python json output")?;

    assert_eq!(ids_rust, py_ids, "tokenizer parity mismatch with Python");
    Ok(())
}

#[test]
fn t05_prompt_tail_contains_assistant_only() -> Result<()> {
    let snapshot = expand_tilde(SNAPSHOT);
    let msg = Message::from_role_and_content(
        Role::User,
        "Explain what MXFP4 quantization is".to_string(),
    );
    let ids = render_then_encode(&snapshot, &[msg], true)?;

    let tok_path = snapshot.join("tokenizer.json");
    let tk = tokenizers::Tokenizer::from_file(&tok_path)
        .map_err(|e| anyhow::anyhow!("failed to load tokenizer.json: {e}"))?;
    let decoded = match tk.decode(&ids, /*skip_special_tokens=*/ false) {
        Ok(s) => s,
        Err(e) => {
            panic!("decode of rendered prompt failed: {}", e);
        }
    };
    // The official HF chat_template places only "<|start|>assistant" at the tail when add_generation_prompt=True.
    // The channel and message markers are expected to be generated by the model as the first tokens.
    assert!(decoded.contains("<|start|>assistant"));
    assert!(!decoded.contains("<|channel|>final<|message|>"));
    Ok(())
}

#[test]
fn t06_stop_tokens_exact_set_and_no_end() -> Result<()> {
    use gpt_oss_tokenizer::load_stop_token_ids;
    let snapshot = expand_tilde(SNAPSHOT);
    let ids = load_stop_token_ids(&snapshot)?;
    let tok_path = snapshot.join("tokenizer.json");
    let tk = tokenizers::Tokenizer::from_file(&tok_path)
        .map_err(|e| anyhow::anyhow!("failed to load tokenizer.json: {e}"))?;
    let id_eot = tk
        .token_to_id("<|endoftext|>")
        .context("missing <|endoftext|>")?;
    let id_ret = tk.token_to_id("<|return|>").context("missing <|return|>")?;
    let id_call = tk.token_to_id("<|call|>").context("missing <|call|>")?;
    let id_end = tk.token_to_id("<|end|>").context("missing <|end|>")?;
    let set: std::collections::BTreeSet<u32> = ids.iter().copied().collect();
    let expect: std::collections::BTreeSet<u32> = [id_eot, id_ret, id_call].into_iter().collect();
    assert_eq!(set, expect, "stop token id set mismatch");
    assert!(!set.contains(&id_end), "stop set must not include <|end|>");
    Ok(())
}
