use anyhow::Result;
use gpt_oss_tokenizer::render_then_encode;
use openai_harmony::chat::{Message, Role};

const SNAPSHOT_DIR: &str = "~/.cache/huggingface/hub/models--openai--gpt-oss-20b/snapshots/6cee5e81ee83917806bbde320786a8fb61efebee";

fn p(s: &str) -> std::path::PathBuf {
    if let Some(rest) = s.strip_prefix("~/") {
        std::env::var("HOME").map(std::path::PathBuf::from).unwrap().join(rest)
    } else {
        std::path::PathBuf::from(s)
    }
}

// Ensure chat_template.jinja renders the assistant boundary and final-channel header
// without any manual prefill/stitching.
#[test]
fn t25_render_then_encode_includes_assistant_final_header() -> Result<()> {
    let dir = p(SNAPSHOT_DIR);
    let msg = Message::from_role_and_content(Role::User, "What is MXFP4?" );
    let tokens = render_then_encode(&dir, &[msg], true)?;

    // Load tokenizer.json to decode the rendered ids.
    let tok = tokenizers::Tokenizer::from_file(dir.join("tokenizer.json"))
        .map_err(|e| anyhow::anyhow!("failed to load tokenizer.json: {e}"))?;
    let decoded = tok.decode(&tokens, /*skip_special_tokens=*/ false)
        .unwrap_or_else(|_| String::from(""));

    // Boundary must contain an assistant header. Newline presence is template-dependent.
    assert!(decoded.contains("<|start|>assistant"), "assistant header missing: {}", decoded);
    // The final-channel header is not part of the generation prompt; it is expected to be generated by the model.
    assert!(!decoded.contains("<|channel|>final<|message|>"), "final-channel header should not be present in prompt: {}", decoded);
    Ok(())
}
